// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Data
{


    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class GdShowContext : System.Data.Entity.DbContext, IGdShowContext
    {
        public System.Data.Entity.DbSet<Set> Sets { get; set; } // Set
        public System.Data.Entity.DbSet<Show> Shows { get; set; } // Show
        public System.Data.Entity.DbSet<Song> Songs { get; set; } // Song
        public System.Data.Entity.DbSet<SongRef> SongRefs { get; set; } // SongRef
        public System.Data.Entity.DbSet<User> Users { get; set; } // User

        static GdShowContext()
        {
            System.Data.Entity.Database.SetInitializer<GdShowContext>(null);
        }

        public GdShowContext()
            : base("Name=Context")
        {
        }

        public GdShowContext(string connectionString)
            : base(connectionString)
        {
        }

        public GdShowContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
        }

        public GdShowContext(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
        }

        public GdShowContext(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(System.Data.SqlClient.SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as System.Data.SqlTypes.INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == System.DBNull.Value);
        }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new SetConfiguration());
            modelBuilder.Configurations.Add(new ShowConfiguration());
            modelBuilder.Configurations.Add(new SongConfiguration());
            modelBuilder.Configurations.Add(new SongRefConfiguration());
            modelBuilder.Configurations.Add(new UserConfiguration());
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new SetConfiguration(schema));
            modelBuilder.Configurations.Add(new ShowConfiguration(schema));
            modelBuilder.Configurations.Add(new SongConfiguration(schema));
            modelBuilder.Configurations.Add(new SongRefConfiguration(schema));
            modelBuilder.Configurations.Add(new UserConfiguration(schema));
            return modelBuilder;
        }
    }
}
// </auto-generated>
