// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Data
{

    // Set
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Set: BaseEntity
    {
        
        public System.Guid ShowId { get; set; } // ShowId
        public byte? SetNumber { get; set; } // SetNumber
        public bool IsEncore { get; set; } // IsEncore

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Song> Songs { get; set; } // Song.FK_Song_Set

        // Foreign keys
        public virtual Show Show { get; set; } // FK_Set_Show

        public Set()
        {
            Songs = new System.Collections.Generic.List<Song>();
        }
    }

}
// </auto-generated>
