// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Data
{

    // Show
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Show: BaseEntity
    {
        
        public System.DateTime? ShowDate { get; set; } // ShowDate
        public string Venue { get; set; } // Venue (length: 256)
        public string City { get; set; } // City (length: 64)
        public string State { get; set; } // State (length: 32)
        public string Country { get; set; } // Country (length: 64)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Set> Sets { get; set; } // Set.FK_Set_Show

        public Show()
        {
            Sets = new System.Collections.Generic.List<Set>();
        }
    }

}
// </auto-generated>
