// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Data
{

    // Show
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class ShowConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Show>
    {
        public ShowConfiguration()
            : this("dbo")
        {
        }

        public ShowConfiguration(string schema)
        {
            ToTable("Show", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").IsRequired().HasColumnType("uniqueidentifier").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ShowDate).HasColumnName(@"ShowDate").IsOptional().HasColumnType("date");
            Property(x => x.Venue).HasColumnName(@"Venue").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(256);
            Property(x => x.City).HasColumnName(@"City").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(64);
            Property(x => x.State).HasColumnName(@"State").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(32);
            Property(x => x.Country).HasColumnName(@"Country").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(64);
        }
    }

}
// </auto-generated>
