// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Data
{

    // Song
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Song: BaseEntity
    {
        
        public System.Guid SetId { get; set; } // SetId
        public System.Guid SongRefId { get; set; } // SongRefId
        public byte Position { get; set; } // Position
        public bool IsSegued { get; set; } // IsSegued

        // Foreign keys
        public virtual Set Set { get; set; } // FK_Song_Set
        public virtual SongRef SongRef { get; set; } // FK_Song_SongRef
    }

}
// </auto-generated>
