// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Data
{

    // User
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class User: BaseEntity
    {
        
        public string PasswordHash { get; set; } // PasswordHash (length: 256)
        public string PasswordSalt { get; set; } // PasswordSalt (length: 256)
        public Models.ViewModels.UserType UserType { get; set; } // UserType
        public string FirstName { get; set; } // FirstName (length: 64)
        public string LastName { get; set; } // LastName (length: 64)
        public string EmailAddress { get; set; } // EmailAddress (length: 128)
        public Models.ViewModels.UserStatusType Status { get; set; } // Status
        public System.DateTimeOffset? PasswordExpire { get; set; } // PasswordExpire
        public int AccessFailedCount { get; set; } // AccessFailedCount
        public System.DateTimeOffset? LockoutEnd { get; set; } // LockoutEnd

        public User()
        {
            AccessFailedCount = 0;
        }
    }

}
// </auto-generated>
